# -*- coding: utf-8 -*-
"""BMI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VYAat1AoFgCDyeLQzmbycTzmyYA-tQSj
"""

h=float(input("Enter your height in meters: "))
w=float(input("Enter your Weight in Kg: "))
BMI=w/(h*h)
print("BMI Calculated is:  ",BMI)
if(BMI>0):
    if(BMI<=16):
        print("You are very underweight")
    elif(BMI<=18.5):
        print("You are underweight")
    elif(BMI<=25):
        print("You are normal")
    elif(BMI<=30):
        print("You are overweight")
    else:
        print("You are very overweight")
else:
    print("enter valid details")